package fr.LaurentFE.pacManClone;

public enum TileType {
    PATH,
    SIMPLEVERTICALWALL,
    DOUBLEVERTICALWALL,
    SIMPLEHORIZONTALWALL,
    DOUBLEHORIZONTALWALL,
    SIMPLEINNERUPLEFTCORNER,
    DOUBLEINNERUPLEFTCORNER,
    SIMPLEINNERUPRIGHTCORNER,
    DOUBLEINNERUPRIGHTCORNER,
    SIMPLEINNERDOWNRIGHTCORNER,
    DOUBLEINNERDOWNRIGHTCORNER,
    SIMPLEINNERDOWNLEFTCORNER,
    DOUBLEINNERDOWNLEFTCORNER,
    SIMPLEOUTERUPLEFTCORNER,
    DOUBLEOUTERUPLEFTCORNER,
    SIMPLEOUTERUPRIGHTCORNER,
    DOUBLEOUTERUPRIGHTCORNER,
    SIMPLEOUTERDOWNLEFTCORNER,
    DOUBLEOUTERDOWNLEFTCORNER,
    SIMPLEOUTERDOWNRIGHTCORNER,
    DOUBLEOUTERDOWNRIGHTCORNER,
    OUTOFBOUNDS,
    DOOR,
    UNDEFINED

}
